server:
  port: 8085
eureka:
  instance:
    hostname: localhost
    appname: provider1
    instance-id: provider1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: provider1
