server:
  port: 8001
spring:
  application:
    name: comsumer1
  mvc:
    static-path-pattern: /static/**
#  mvc:
#    view:
#      prefix: /
#      suffix: .html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
info:
  appname: 我是来自消费端
  extra: test
management:
  endpoints:
    web:
      exposure:
        include: "*"